name: Constructor
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar herramientas de empaquetado
      run: |
        sudo apt update
        sudo apt install -y debootstrap squashfs-tools
      
    - name: Descargar y Crear Base Debian 12 (Bookworm)
      run: |
        echo "=== DESCARGANDO BASE DE DEBIAN 12 DESDE INTERNET ==="
        sudo debootstrap --variant=minbase bookworm ./debian-base http://deb.debian.org/debian/
        echo "¡Base descargada con éxito en la carpeta ./debian-base!"

    - name: Inyectar interfaz AeroMac-OS
      run: |
        echo "=== INYECTANDO NUESTROS SCRIPT DE INTERFAZ ==="
        sudo cp interfaz/instalador.sh ./debian-base/tmp/
        echo "El instalador visual ya está dentro del sistema de archivos de Debian."

    - name: Ejecutar instalador dentro de AeroMac-OS
      run: |
        echo "=== ENTRANDO A AEROMAC-OS MEDIANTE CHROOT ==="
        sudo cp /etc/resolv.conf ./debian-base/etc/resolv.conf
        sudo chroot ./debian-base /bin/bash /tmp/instalador.sh
        echo "¡La interfaz gráfica ha sido instalada con éxito dentro del sistema!"
        
    - name: Convertir AeroMac-OS en formato SquashFS
      run: |
        echo "=== COMPRIMIENDO EL SISTEMA OPERATIVO ==="
        sudo mksquashfs ./debian-base filesystem.squashfs -comp xz
        echo "¡AeroMac-OS ha sido empaquetado con éxito en un solo archivo ejecutable!"
